"""
Kitsune REST API — query the Redis threat intel store.

Run with:
    uvicorn api:app --reload --port 8000

Swagger UI:  http://localhost:8000/docs
Redoc:       http://localhost:8000/redoc
"""

import os
import sys
from typing import Dict, List, Optional

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.openapi.docs import get_swagger_ui_html
from fastapi.responses import HTMLResponse
from pydantic import BaseModel

load_dotenv()

# Allow running from repo root without installing the package
sys.path.insert(0, os.path.dirname(__file__))
from intel_store import create_store

app = FastAPI(
    title="Kitsune Threat Intel API",
    description=(
        "Query the Redis-backed IOC and detection-rule store generated by "
        "the Kitsune threat-intelligence pipeline."
    ),
    version="0.2.0",
    contact={"name": "Kitsune", "url": "https://github.com/christina23/kitsune"},
    docs_url=None,   # disabled; custom Swagger served at /docs
    redoc_url=None,  # disabled; Scalar served at /scalar
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET"],
    allow_headers=["*"],
)


# ── Custom Swagger UI with dark-mode toggle ───────────────────────────────────

_DARK_CSS = """
body.dark { background: #0d1117; }
body.dark .swagger-ui { background: #0d1117; color: #e6edf3; }
body.dark .swagger-ui .topbar { background: #161b22; border-bottom: 1px solid #30363d; }
body.dark .swagger-ui .topbar a { color: #79c0ff; }

/* Info / title block */
body.dark .swagger-ui .info { background: transparent; }
body.dark .swagger-ui .info .title { color: #e6edf3; }
body.dark .swagger-ui .info p,
body.dark .swagger-ui .info li { color: #a8c8e8; }
body.dark .swagger-ui .info a { color: #79c0ff; }
body.dark .swagger-ui .info .base-url { color: #adbac7; }

/* Servers / scheme bar */
body.dark .swagger-ui .scheme-container { background: #161b22; box-shadow: none; border-bottom: 1px solid #30363d; }

/* Section tag headers (Actors, IOCs, etc.) */
body.dark .swagger-ui .opblock-tag { color: #a8c8e8; border-bottom: 1px solid #30363d; }
body.dark .swagger-ui .opblock-tag small { color: #a8c8e8; }
body.dark .swagger-ui .opblock-tag:hover { background: #1c2128; }

/* Operation blocks */
body.dark .swagger-ui .opblock { border-color: #30363d; background: #161b22; }
body.dark .swagger-ui .opblock .opblock-summary { border-color: #30363d; }
body.dark .swagger-ui .opblock .opblock-summary-path,
body.dark .swagger-ui .opblock .opblock-summary-path__deprecated { color: #e6edf3; }
body.dark .swagger-ui .opblock .opblock-summary-description { color: #a8c8e8; }

/* GET */
body.dark .swagger-ui .opblock.opblock-get { background: #111d2e; border-color: #2d5a9e; }
body.dark .swagger-ui .opblock.opblock-get .opblock-summary { border-color: #2d5a9e; }
body.dark .swagger-ui .opblock.opblock-get .opblock-summary-method { background: #1f6feb; }
/* POST */
body.dark .swagger-ui .opblock.opblock-post { background: #0f2218; border-color: #2ea043; }
body.dark .swagger-ui .opblock.opblock-post .opblock-summary-method { background: #238636; }
/* DELETE */
body.dark .swagger-ui .opblock.opblock-delete { background: #200d0e; border-color: #8e2a2a; }
body.dark .swagger-ui .opblock.opblock-delete .opblock-summary-method { background: #da3633; }

/* Expanded body */
body.dark .swagger-ui .opblock-body { background: #0d1117; }
body.dark .swagger-ui .opblock-description-wrapper p,
body.dark .swagger-ui .opblock-external-docs-wrapper p,
body.dark .swagger-ui .opblock-title_normal p { color: #a8c8e8; }

/* Tables */
body.dark .swagger-ui table thead tr th,
body.dark .swagger-ui table thead tr td { color: #adbac7; border-bottom: 1px solid #30363d; }
body.dark .swagger-ui table tbody tr td { color: #cdd9e5; border-bottom: 1px solid #21262d; }

/* Parameters */
body.dark .swagger-ui .parameter__name { color: #e6edf3; }
body.dark .swagger-ui .parameter__type { color: #79c0ff; }
body.dark .swagger-ui .parameter__deprecated { color: #f85149; }
body.dark .swagger-ui .parameter__in { color: #adbac7; font-style: italic; }

/* Form inputs */
body.dark .swagger-ui input[type=text],
body.dark .swagger-ui input[type=password],
body.dark .swagger-ui input[type=email],
body.dark .swagger-ui textarea,
body.dark .swagger-ui select {
    background: #1c2128; color: #e6edf3;
    border: 1px solid #30363d; border-radius: 4px;
}

/* Buttons */
body.dark .swagger-ui .btn { color: #cdd9e5; border-color: #30363d; background: #21262d; }
body.dark .swagger-ui .btn:hover { background: #30363d; color: #e6edf3; }
body.dark .swagger-ui .btn.execute { background: #1f6feb; border-color: #1f6feb; color: #fff; }
body.dark .swagger-ui .btn.execute:hover { background: #388bfd; }
body.dark .swagger-ui .btn.cancel { background: #da3633; border-color: #da3633; color: #fff; }

/* Responses */
body.dark .swagger-ui .responses-inner h4,
body.dark .swagger-ui .responses-inner h5 { color: #e6edf3; }
body.dark .swagger-ui .response-col_status { color: #e6edf3; }
body.dark .swagger-ui .response-col_description { color: #cdd9e5; }
body.dark .swagger-ui .response-col_description p { color: #cdd9e5; }

/* Code / syntax */
body.dark .swagger-ui .highlight-code { background: #161b22 !important; }
body.dark .swagger-ui .microlight { background: #161b22 !important; color: #e6edf3 !important; }

/* Models */
body.dark .swagger-ui section.models { border: 1px solid #30363d; }
body.dark .swagger-ui section.models h4 { color: #e6edf3; }
body.dark .swagger-ui .model-box { background: #161b22; }
body.dark .swagger-ui .model { color: #cdd9e5; }
body.dark .swagger-ui .model-title { color: #79c0ff; }
body.dark .swagger-ui .prop-type { color: #79c0ff; }
body.dark .swagger-ui .prop-format { color: #adbac7; }
body.dark .swagger-ui span.token { color: #79c0ff !important; }

/* Markdown */
body.dark .swagger-ui .markdown p,
body.dark .swagger-ui .markdown li { color: #cdd9e5; }
body.dark .swagger-ui .markdown code { background: #1c2128; color: #e6edf3; border-radius: 3px; padding: 0 4px; }

/* Auth / dialogs */
body.dark .swagger-ui .auth-wrapper { background: #161b22; }
body.dark .swagger-ui .dialog-ux .modal-ux { background: #161b22; border: 1px solid #30363d; }
body.dark .swagger-ui .dialog-ux .modal-ux-header { border-bottom: 1px solid #30363d; }
body.dark .swagger-ui .dialog-ux .modal-ux-header h3 { color: #e6edf3; }
"""

_TOGGLE_JS = """
(function () {
  const KEY = 'kitsune-docs-theme';
  const btn = document.createElement('button');
  btn.id = 'theme-toggle';
  btn.title = 'Toggle dark / light mode';
  btn.style.cssText = [
    'position:fixed', 'top:12px', 'right:18px', 'z-index:9999',
    'background:transparent', 'border:1px solid #30363d', 'border-radius:20px',
    'padding:4px 10px', 'font-size:17px', 'cursor:pointer',
    'line-height:1.4', 'transition:background .15s',
  ].join(';');

  function applyTheme(dark) {
    document.body.classList.toggle('dark', dark);
    btn.textContent = dark ? '☀️' : '🌙';
    btn.style.background = dark ? '#21262d' : '#f0f0f0';
    localStorage.setItem(KEY, dark ? 'dark' : 'light');
  }

  btn.addEventListener('click', function () {
    applyTheme(!document.body.classList.contains('dark'));
  });

  // Apply saved preference immediately, default to dark
  const saved = localStorage.getItem(KEY);
  applyTheme(saved !== 'light');

  // Wait for SwaggerUI to mount before appending the button
  function mount() {
    const topbar = document.querySelector('.topbar') || document.body;
    topbar.appendChild(btn);
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', mount);
  } else {
    mount();
  }
})();
"""


@app.get("/docs", include_in_schema=False)
async def custom_swagger_ui() -> HTMLResponse:
    base: HTMLResponse = get_swagger_ui_html(
        openapi_url=app.openapi_url,
        title=app.title + " — API Docs",
        swagger_ui_parameters={"defaultModelsExpandDepth": -1},
    )
    html = base.body.decode()

    # Inject fox favicon into <head>
    fox_favicon = (
        "<link rel='icon' href=\"data:image/svg+xml,"
        "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'>"
        "<text y='.9em' font-size='90'>🦊</text></svg>\">"
    )
    html = html.replace("</head>", fox_favicon + "</head>")

    # Inject dark-mode CSS and toggle JS just before </body>
    injection = f"<style>{_DARK_CSS}</style><script>{_TOGGLE_JS}</script>"
    html = html.replace("</body>", injection + "</body>")
    return HTMLResponse(html)


@app.get("/scalar", include_in_schema=False)
async def scalar_ui() -> HTMLResponse:
    fox_favicon = (
        "data:image/svg+xml,"
        "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'>"
        "<text y='.9em' font-size='90'>🦊</text></svg>"
    )
    html = f"""<!doctype html>
<html>
  <head>
    <title>{app.title} — API Reference</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="{fox_favicon}">
  </head>
  <body>
    <script
      id="api-reference"
      data-url="{app.openapi_url}"
      data-configuration='{{"theme": "moon", "defaultHttpClient": {{"targetKey": "python", "clientKey": "requests"}}}}'
    ></script>
    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
  </body>
</html>"""
    return HTMLResponse(html)


# ── Pydantic response models ──────────────────────────────────────────────────


class IOCRecord(BaseModel):
    type: str
    value: str
    first_seen: Optional[str] = None
    last_seen: Optional[str] = None
    threat_actors: Optional[str] = None  # JSON-encoded list
    campaigns: Optional[str] = None
    ttps: Optional[str] = None
    source_urls: Optional[str] = None


class RuleRecord(BaseModel):
    name: str
    format: str
    ttps: Optional[str] = None  # JSON-encoded list
    threat_actor: Optional[str] = None
    source_url: Optional[str] = None
    created_at: Optional[str] = None


class TrendingTTP(BaseModel):
    ttp_id: str
    count: int


class CoverageEntry(BaseModel):
    ttp_id: str
    has_iocs: bool
    has_rules: bool
    ioc_count: int
    rule_count: int


class ActorSummary(BaseModel):
    actor: str
    total_iocs: int
    total_rules: int
    ioc_counts: Dict[str, int]
    ttps: List[str]
    campaigns: List[str]


class HealthResponse(BaseModel):
    status: str
    redis: str


# ── Dependency ────────────────────────────────────────────────────────────────


def get_store():
    store = create_store()
    if store is None:
        raise HTTPException(
            status_code=503,
            detail=(
                "Redis store unavailable. "
                "Set REDIS_URL in your environment (e.g. redis://localhost:6379)."
            ),
        )
    return store


# ── Routes ────────────────────────────────────────────────────────────────────


@app.get("/", response_model=HealthResponse, tags=["Health"])
def health_check():
    """Returns API status and Redis connectivity."""
    store = create_store()
    redis_status = "connected" if store is not None else "unavailable"
    return {"status": "ok", "redis": redis_status}


@app.get("/actors", response_model=List[str], tags=["Actors"])
def list_actors():
    """
    Return all threat actors that have been ingested into the store.
    """
    store = get_store()
    actors = store._r.smembers(store._actors_key())
    return sorted(actors)


@app.get("/actors/{actor_name}/summary", response_model=ActorSummary, tags=["Actors"])
def actor_summary(actor_name: str):
    """
    Return a summary for a specific threat actor:
    IOC type breakdown, associated TTPs, and campaigns.

    **Example:** `/actors/apt28/summary`
    """
    store = get_store()
    result = store.get_actor_summary(actor_name)
    if result["total_iocs"] == 0 and result["total_rules"] == 0:
        raise HTTPException(status_code=404, detail=f"Actor '{actor_name}' not found.")
    return result


@app.get("/iocs", response_model=List[IOCRecord], tags=["IOCs"])
def query_iocs(
    actor: Optional[str] = Query(None, description="Filter by threat actor name"),
    ttp: Optional[str] = Query(None, description="Filter by MITRE ATT&CK technique ID (e.g. T1059)"),
    ioc_type: Optional[str] = Query(
        None,
        description="Filter by IOC type",
        enum=["ip", "domain", "hash", "file", "url"],
    ),
    limit: int = Query(100, ge=1, le=1000, description="Maximum results to return"),
):
    """
    Query IOCs from the threat intel store.

    Filters can be combined — e.g. actor + ttp returns the intersection.

    **Example:** `/iocs?actor=apt28&ttp=T1059&limit=25`
    """
    store = get_store()
    results = store.query_iocs(actor=actor, ttp=ttp, ioc_type=ioc_type, limit=limit)
    return results


@app.get("/rules", response_model=List[RuleRecord], tags=["Detection Rules"])
def query_rules(
    actor: Optional[str] = Query(None, description="Filter by threat actor name"),
    ttp: Optional[str] = Query(None, description="Filter by MITRE ATT&CK technique ID"),
    limit: int = Query(100, ge=1, le=1000, description="Maximum results to return"),
):
    """
    Query detection rules (Sigma / SPL) from the store.

    **Example:** `/rules?ttp=T1059&limit=10`
    """
    store = get_store()
    results = store.query_rules(actor=actor, ttp=ttp, limit=limit)
    return results


@app.get("/trends", response_model=List[TrendingTTP], tags=["Analytics"])
def trending_ttps(
    top: int = Query(10, ge=1, le=100, description="Number of top TTPs to return"),
):
    """
    Return the top-N MITRE ATT&CK techniques by ingestion frequency.

    **Example:** `/trends?top=20`
    """
    store = get_store()
    return store.get_trending_ttps(n=top)


@app.get("/coverage", response_model=List[CoverageEntry], tags=["Analytics"])
def coverage_summary():
    """
    Per-TTP coverage report: whether each technique has associated IOCs
    and/or detection rules in the store.
    """
    store = get_store()
    raw = store.get_coverage_summary()
    return [{"ttp_id": ttp_id, **data} for ttp_id, data in sorted(raw.items())]
